### PR TITLE
Fix/player events

### PR DESCRIPTION
**Pull request by jspizziri**

### CODE REVIEW

**Comment by doughsay** [comment]
> @mpivchev in _theory_ I think this should be working, but there's another snag now.
> 
> The `MediaSessionCompat.Callback` override events aren't getting fired. Example: [`onPlay`](https://github.com/doublesymmetry/KotlinAudio/pull/33/files#diff-7d05808a134fc6efdaef2d0049ac5bf23ee4367c6c2601f159b4577f6bbb29bfR179) isn't getting called when a remote play button is pressed. This is the case for _all_ hooks except for `onSeekTo`, which gets called as expected.
> 
> Any ideas on this?

I tested this branch on a real device with a modified RNTP and I do get the media session callback events (at least play and pause) but only if triggered from a connected bluetooth device.  Tapping the notification buttons does not trigger the events.

**Comment by jspizziri** [comment]
@doughsay thanks for the feedback. I think I see my mistake, v2.1 actually [registers a `BroadcastReceiver`](https://github.com/doublesymmetry/react-native-track-player/blob/v2.1/android/src/main/java/com/guichaguri/trackplayer/module/MusicModule.java#L54) which I think is handling the button taps themselves. I mistakenly thought the only place they were being emitted was from the callback.

I'm going to do some more exploration on this, but I think your suggestion to _not_ remove the local event handling for player button tapping is correct. Stay tuned.

**Comment by Hannes1** [comment]
Any estimate for when this will get merged?

**Comment by jspizziri** [comment]
@Hannes1 this PR in its current state doesn't work the way it had been hoped. We're working on a different solution but it's going to be a bit longer.

**Comment by mpivchev** [comment]
This is handled here #38

**Pull request closed without merging**
